[package]
name = "nowayjose_testutils"
version = "0.1.0"
authors = ["Sonny Scroggin <sonny@scrogg.in>"]
edition = "2018"

[lib]
name = "nowayjose_testutils"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.21"
openssl = "0.10"
